src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $user;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Price;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="participation")
     */
    private $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(?float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addParticipation($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            $user->removeParticipation($this);
        }

        return $this;
    }
}

src/Controller/ParticipeController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Entity\User;
use App\Form\ConfirmDeletionFormType;
use App\Repository\EventRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;

class ParticipeController extends AbstractController
{

    private $manager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->manager = $entityManager;
    }


    /**
     * @Route("/part/{id}", name="participe_event")
     * @IsGranted("ROLE_USER")
     */
    public function index(Event $event)
    {
            $this->addFlash('success', 'Vous participer à l\'événemnt');
            return $this->redirectToRoute('event_page', ['id' => $event->getId()]);
    }


    /**
     * @Route("/add_part/{id}", name="participe_profil")
     * * @IsGranted("ROLE_USER")
     */
    public function add_parti(Event $event, Request $request)
    {
        $token = $request->query->get('token');
        if ($this->isCsrfTokenValid('event_participation', $token)) {
 
           $this->getUser()->addParticipation($event);
            $this->manager->flush();
        }

        $this->addFlash('success', 'Vous avez participez à notre événement.');
        return $this->redirectToRoute('event_page', ['id' => $event->getId()]);
    }


    /**
     * supprimer particpation a un event par la page lister les evenement pour public
     * @Route("/delete_part/{id}", name="participe_profil_delete")
     *
     */
    public function delete_parti(Event $event, Request $request)
    {
        $deleteForm = $this->createForm(ConfirmDeletionFormType::class);
        $deleteForm->handleRequest($request);

        //dd($deleteForm);


        if ($deleteForm->isSubmitted() && $deleteForm->isValid())
        {
            $token = $request->query->get('token');
            if ($this->isCsrfTokenValid('delete_event', $token))
            {

                $this->getUser()->removeParticipation($event);
                $this->manager->flush();
            }

            $this->addFlash('danger', 'Vous avez annuler votre participation à l\'événement');
            return $this->redirectToRoute('event_page', ['id' => $event->getId()]);
        }
        return $this->render('event/event_delete.html.twig', [
            'event' => $event,
            'delete_form' => $deleteForm->createView(),
        ]);


    }



    /**
     * suppression evenement
     * @Route("/event_delete/{id}", name="event_delete")
     * @IsGranted("DELETE_EVENT", subject="event")
     */
    public function supprim(Event $event, Request $request)
    {
        $deleteForm = $this->createForm(ConfirmDeletionFormType::class);
         $deleteForm->handleRequest($request);

         if ($deleteForm->isSubmitted() && $deleteForm->isValid()) {
            $this->manager->remove($event);
            $this->manager->flush();

            $this->addFlash('danger', 'L\'événement a été supprimée');
            return $this->redirectToRoute('liste_event_profil', [
                'id' => $event->getUser()->getId(),
            ]);
        }

        return $this->render('event/event_delete.html.twig', [
            'event' => $event,
            'delete_form' => $deleteForm->createView(),
        ]);

    }


    



    /**
     * Liste participation par profil
     * @Route("/Liste_part", name="participe_profil_liste")
     */
    public function liste_parti(EventRepository $eventRepository)
    {
        $event = $eventRepository->findBy(['user' => $this->getUser()]);
            //dd($event);
        return $this->render('participe/liste_part_profil.html.twig',[
            'event' => $event,
        
        ]);
    }


    /**
     * supprimer une participation à un event depuis la page liste particiaption de l'utilisateur
     * @Route("/delete_part_profil/{id}", name="delete_participe_profil")
     *
     */
    public function delete_parti_prof(Event $event, Request $request)
    {
        $deleteForm = $this->createForm(ConfirmDeletionFormType::class);
        $deleteForm->handleRequest($request);

        if ($deleteForm->isSubmitted() && $deleteForm->isValid())
        {
            $token = $request->query->get('token');
            if ($this->isCsrfTokenValid('delete_event', $token)) {

                $this->getUser()->removeParticipation($event);
                $this->manager->flush();
            }

            $this->addFlash('danger', 'Vous avez annuler votre participation à l\'événement');
            return $this->render('participe/liste_part_profil.html.twig');

        }

        return $this->render('event/event_delete.html.twig', [
            'event' => $event,
            'delete_form' => $deleteForm->createView(),
        ]);


    }




}

templates/participe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ParticipeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Users/Seifo/Desktop/Symfony/AddEventWeb/src/Controller/ParticipeController.php'|file_link(0) }}">src/Controller/ParticipeController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Users/Seifo/Desktop/Symfony/AddEventWeb/templates/participe/index.html.twig'|file_link(0) }}">templates/participe/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/participe/liste_part_profil.html.twig
{% extends '_template.html.twig' %}

{% block title %} Participation liste {% endblock %}

{% block content %}
    {% include 'includes/flash.html.twig' %}
    <div class="section">
        <div class="box">
            <article class="media">
              <div class="media-left">
                <figure class="image is-64x64">
                    <img class="is-rounded" src="https://robohash.org/{{ app.user.nom }}?set=set5">
                </figure>
              </div>
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong class="title">{{ app.user.pseudo}}</strong>
                    <br>
                    <strong class="has-text-primary">Participation liste:</strong><br>
                    Vous participez à {{ app.user.participation|length }} évenements.
                  </p>
                </div>
            </div>
        </div>

        {% for particip in app.user.participation %}
            <div class="columns box">
                <div class="column">
                    <article class="media">
                        <div class="media-left">
                            <figure class="image is-128x128">
                                <img src="https://loremflickr.com/256/256/happy/all?" alt="Image">
                            </figure>
                        </div>
                        <div class="media-content is-mobile">
                            <div class="content is-three-fifths is-offset-one-fifth">
                                <p>
                                    <a href="" class="has-text-primary">
                                        <strong>{{particip.nom}}</strong>
                                    </a>
                                    <br>
                                    <small>Date: {{ particip.date|date('d/m/Y')}}</small>
                                    <br>
                                    <small>Description: {{ particip.description|slice(0, 50)}}</small><br>
                                    <small>prix: {{ particip.price}}€</small><br>
                                    <div class="field ">
                                        {% if is_granted("EVENT_PARTICIPATION", particip ) %}
                                            <p class="control">
                                            <a class="button is-danger" href="{{path('delete_participe_profil', {id: particip.id, token:csrf_token('delete_event')} )}}">
                                                <span><i class="fas fa-trash-alt"></i>&ensp;</span>
                                                Cancel
                                            </a>
                                            </p>
                                        {% endif %}
                                    </div>
                                </p>
                            </article>
                        </div>
                            {# /////// #}
                            <div class="column is-three-fifths">
                                <article class="media is-centered ">
                                    <div class="media-content is-mobile">
                                            <strong class="has-text-primary">Liste des participants: {{ particip.users|length }}</strong>

                                            <br><br>
                                            <div class="columns is-multiline">
                                                {% for item in particip.users %}
                                                    <div class="column is-one-fifth">
                                                        <figure class="image is-32x32">
                                                            <img class="is-rounded" src="https://robohash.org/{{ item.nom }}?set=set5">
                                                        </figure>
                                                        <div>{{item.pseudo}}</div>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                    </div>
                                </article>
                            </div>


                        </div><br>

                    </div>
                </div>  

    {% endfor %}


</div>


{% endblock %}

templates/participe/mail.participe.html.twig
{% extends "_template.html.twig" %}

{% block title %}Envoyer Event{% endblock %}

{% block content %}
  
        
    
        <div class="columns is-mobile section">
            <h1 class="box title column is-three-fifths is-offset-one-fifth">
                <span><i class="fas fa-envelope"></i></span>
                Inviter un ami par email: 
            </h1>
        </div>

        {# Formuliare : pour envoyer un mail  #}
        <div class="columns is-centered ">
            <div class="column is-three-fifths box">

        {{ form_start(mail_event) }}
            {{ form_row(mail_event.email, {label: 'Titre:'}) }}
            {{ form_row(mail_event.description, {label: 'Contenu:'}) }}
            <button type="submit" class="button is-primary is-fullwidth">Envoyer</button>
        
        {{ form_end(mail_event) }}
    </div>
{% endblock %}